import pandas as pd
import yfinance as yf
import sys
import os
import numpy as np
sys.path.append('d:/FOREX/FOREX')
from lk_system.core.smc_engine import SMCEngine

class BacktestEngine:
    """
    Executes trades generated by the SMCEngine over historical data.
    Enforces a strict 1:6 Risk to Reward ratio on all trades.
    Uses Limit Orders based on FVG mitigations.
    """
    def __init__(self, initial_capital=10000.0, risk_per_trade=0.01):
        self.initial_capital = initial_capital
        self.risk_per_trade = risk_per_trade
        self.rr_ratio = 6.0
        
        self.capital = initial_capital
        self.trades = []
        
    def run(self, df):
        print(f"Starting Backtest on {len(df)} bars...")
        engine = SMCEngine()
        df_signals = engine.generate_signals(df)
        
        active_trade = None
        
        for i in range(len(df_signals)):
            curr = df_signals.iloc[i]
            dt = df_signals.index[i]
            
            # If we are in a trade, check if it hit TP or SL
            if active_trade:
                if active_trade['type'] == 'long':
                    if curr['Low'] <= active_trade['sl']:
                        active_trade['exit_price'] = active_trade['sl']
                        active_trade['exit_time'] = dt
                        active_trade['pnl'] = -self.risk_per_trade * self.capital
                        self.capital += active_trade['pnl']
                        self.trades.append(active_trade)
                        active_trade = None
                    elif curr['High'] >= active_trade['tp']:
                        active_trade['exit_price'] = active_trade['tp']
                        active_trade['exit_time'] = dt
                        active_trade['pnl'] = (self.risk_per_trade * self.rr_ratio) * self.capital
                        self.capital += active_trade['pnl']
                        self.trades.append(active_trade)
                        active_trade = None
                        
                elif active_trade['type'] == 'short':
                    if curr['High'] >= active_trade['sl']:
                        active_trade['exit_price'] = active_trade['sl']
                        active_trade['exit_time'] = dt
                        active_trade['pnl'] = -self.risk_per_trade * self.capital
                        self.capital += active_trade['pnl']
                        self.trades.append(active_trade)
                        active_trade = None
                    elif curr['Low'] <= active_trade['tp']:
                        active_trade['exit_price'] = active_trade['tp']
                        active_trade['exit_time'] = dt
                        active_trade['pnl'] = (self.risk_per_trade * self.rr_ratio) * self.capital
                        self.capital += active_trade['pnl']
                        self.trades.append(active_trade)
                        active_trade = None
            
            # If no active trade, look for mitigated signals
            if not active_trade and curr['Signal'] != 0:
                entry = curr['Limit_Entry_Price']
                sl = curr['Stop_Loss_Price']
                
                # Failsafe in case SL and Entry are identical (prevents div by zero or flat trades)
                if pd.isna(entry) or pd.isna(sl) or entry == sl:
                    continue
                    
                risk_distance = abs(entry - sl)
                
                if curr['Signal'] == 1: # Long
                    tp = entry + (risk_distance * self.rr_ratio)
                    active_trade = {
                        'type': 'long',
                        'setup': curr['Setup'],
                        'entry_time': dt,
                        'entry_price': entry,
                        'sl': sl,
                        'tp': tp
                    }
                elif curr['Signal'] == -1: # Short
                    tp = entry - (risk_distance * self.rr_ratio)
                    active_trade = {
                        'type': 'short',
                        'setup': curr['Setup'],
                        'entry_time': dt,
                        'entry_price': entry,
                        'sl': sl,
                        'tp': tp
                    }
                    
        self._print_report()
        
    def _print_report(self):
        print("\n--- Lewis Kelly SMC Engine: Backtest Report (Phase 4 Refinement) ---")
        total_trades = len(self.trades)
        if total_trades == 0:
            print("No trades executed.")
            return
            
        wins = sum(1 for t in self.trades if t['pnl'] > 0)
        win_rate = (wins / total_trades) * 100
        total_pnl = sum(t['pnl'] for t in self.trades)
        
        print(f"Total Trades: {total_trades}")
        print(f"Win Rate: {win_rate:.2f}%")
        print(f"Starting Capital: ${self.initial_capital:.2f}")
        print(f"Ending Capital: ${self.capital:.2f}")
        print(f"Total Net Profit: ${total_pnl:.2f} ({total_pnl/self.initial_capital * 100:.2f}%)")
        print("--------------------------------------------------------------------")

if __name__ == "__main__":
    print("Downloading 60 days of EURUSD M15 Data...")
    df = yf.download("EURUSD=X", period="60d", interval="15m")
    
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = [c[0] for c in df.columns]
        
    if df.index.tz is None:
        df.index = df.index.tz_localize('UTC').tz_convert('US/Eastern')
    else:
        df.index = df.index.tz_convert('US/Eastern')
        
    backtester = BacktestEngine(initial_capital=10000.0)
    backtester.run(df)
